add empty check to output
i think there's nothing preventing output[1] from being nil

bin/churn_vs_complexity:46:in `block (2 levels) in <main>': undefined method `[]' for nil:NilClass (NoMethodError)